// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHFaPOaXAdBHtrfdB-NQjrDXH8ZwhiOE',
    appId: '1:37507938700:web:6898c8c91ede74fdf83ea9',
    messagingSenderId: '37507938700',
    projectId: 'tuzo-cdcbd',
    authDomain: 'tuzo-cdcbd.firebaseapp.com',
    storageBucket: 'tuzo-cdcbd.firebasestorage.app',
    measurementId: 'G-2J8S81Y266',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDan5Ov0xtInJWBME0EhoB0jdDONWDPLIc',
    appId: '1:37507938700:android:552b07cf44d994b9f83ea9',
    messagingSenderId: '37507938700',
    projectId: 'tuzo-cdcbd',
    storageBucket: 'tuzo-cdcbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7roR_TT8aLA_-dp4Bgl7oUH7f4K33lUc',
    appId: '1:37507938700:ios:1047a339f68c2704f83ea9',
    messagingSenderId: '37507938700',
    projectId: 'tuzo-cdcbd',
    storageBucket: 'tuzo-cdcbd.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
